require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'SampleApp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])  
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec'
  pod 'CustomerIO/Tracking', '~> 1.1'
  pod 'CustomerIO/MessagingPushAPN', '~> 1.1'
  
  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
  # end
end

target 'Notification Service' do
  pod 'CustomerIO/Tracking', '~> 1.1'
  pod 'CustomerIO/MessagingPushAPN', '~> 1.1'  
end

post_install do |installer|
  work_dir = Dir.pwd
  Dir.glob("Pods/Target Support Files/Pods-Demo/*.xcconfig") do |xc_config_filename|
      full_path_name = "#{work_dir}/#{xc_config_filename}"
      xc_config = File.read(full_path_name)
      new_xc_config = new_xc_config.sub(/GCC_PREPROCESSOR_DEFINITIONS/, 'PODS_GCC_PREPROCESSOR_DEFINITIONS')
      File.open(full_path_name, 'w') { |file| file << new_xc_config }
  end

end