name: Create test builds

on:  
  pull_request:

jobs:
  deploy-android-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: npm install because Podfile requires files from it 
        run: yarn --frozen-lockfile

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup environment for building and releasing app
        run: echo "${{ secrets.ENV_FILE_B64 }}" | base64 -d > "env.js" # cat env.js | base64

      - name: Install tools from Gemfile (ruby language) used for building our apps with 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # cache tools to make builds faster in future

      - name: Build app via Fastlane 
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'android build'
          subdirectory: "android"
        env: 
          FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64 }}

  deploy-ios-app:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3 # checkout to be able to run CI config files below

      - name: Set up Xcode to version we determine 
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14

      - name: Install tools from Gemfile (ruby language) used for building our apps with 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # cache tools to make builds faster in future

      - name: Install tools for Fastlane build to use
        run: brew install xcbeautify

      - name: Setup environment for building and releasing app
        run: echo "${{ secrets.ENV_FILE_B64 }}" | base64 -d > "env.js" # cat env.js | base64

      - name: npm install because Podfile requires files from it 
        run: yarn --frozen-lockfile

      - name: pod install as React Native project requires it 
        working-directory: ios 
        run: pod install --repo-update

      - name: Build app via Fastlane 
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: "build"
          subdirectory: "ios"
        env: 
          GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64: ${{ secrets.GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64 }}
          FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64 }}
      